--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '4',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['Mass1'] = {
            ['rectangle'] = RECTANGLE( 140.5, 336.5, 144.5, 340.5 ),
        },
        ['Mass2'] = {
            ['rectangle'] = RECTANGLE( 130.5, 349.5, 134.5, 353.5 ),
        },
        ['Mass3'] = {
            ['rectangle'] = RECTANGLE( 144.5, 362.5, 148.5, 366.5 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 312.5, 24.4668, 196.5 ),
                },
                ['WeatherDefMarker'] = {
                    ['WeatherType02'] = STRING( 'None' ),
                    ['WeatherType03'] = STRING( 'None' ),
                    ['WeatherDriftDirection'] = VECTOR3( 1, 0, 0 ),
                    ['MapStyle'] = STRING( 'Tropical' ),
                    ['WeatherType04Chance'] = FLOAT( 0.100000 ),
                    ['WeatherType01'] = STRING( 'LightStratus' ),
                    ['WeatherType03Chance'] = FLOAT( 0.300000 ),
                    ['type'] = STRING( 'Weather Definition' ),
                    ['hint'] = BOOLEAN( true ),
                    ['WeatherType02Chance'] = FLOAT( 0.300000 ),
                    ['WeatherType01Chance'] = FLOAT( 0.400000 ),
                    ['WeatherType04'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 213.5, 23.1035, 295.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 142.5, 20.6738, 338.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 381.5, 20.5742, 152.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 279.5, 20.4082, 130.5 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 118.5, 20.3828, 328.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 361.5, 20.7598, 158.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 132.5, 20.6387, 351.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 370.5, 20.5879, 144.5 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 329.5, 20.3984, 274.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 372.5, 20.7051, 166.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 125.5, 18.2695, 390.5 ),
                },
                ['Weather Generator 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 289.686, 18.4653, 110.184 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 210.5, 20.6289, 371.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 317.5, 24.2148, 207.5 ),
                },
                ['Weather Generator 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 145.776, 20.646, 359.052 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 275.5, 20.3242, 334.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 184.5, 24.2324, 316.5 ),
                },
                ['Weather Generator 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 342.185, 20.6802, 273.408 ),
                },
                ['Intro_Cam'] = {
                    ['zoom'] = FLOAT( 39.889519 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( -3.14159, 1.02395, 0 ),
                    ['position'] = VECTOR3( 146.808, 20.5487, 347.086 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 146.5, 20.6484, 364.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 391.5, 18.1328, 119.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 172.5, 20.7324, 242.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 184.5, 18.7676, 404.5 ),
                },
                ['Weather Generator 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 389.433, 20.0278, 231.564 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 390.5, 20.4941, 195.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 196.5, 24.793, 321.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 341.5, 20.5547, 139.5 ),
                },
                ['Weather Generator 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 435.105, 18.6172, 412.157 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 235.5, 20.0176, 175.5 ),
                },
                ['Weather Generator 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 70.9852, 18.5703, 89.9907 ),
                },
                ['Weather Generator 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 182.973, 19.7607, 227.326 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 162.5, 20.6582, 355.5 ),
                },
                ['Weather Generator 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['cloudHeight'] = FLOAT( 180.000000 ),
                    ['cloudEmitterScale'] = FLOAT( 1.000000 ),
                    ['cloudEmitterScaleRange'] = FLOAT( 0.000000 ),
                    ['type'] = STRING( 'Weather Generator' ),
                    ['cloudSpread'] = FLOAT( 150.000000 ),
                    ['cloudHeightRange'] = FLOAT( 15.000000 ),
                    ['spawnChance'] = FLOAT( 1.000000 ),
                    ['ForceType'] = STRING( 'None' ),
                    ['color'] = STRING( 'FF808000' ),
                    ['cloudCount'] = FLOAT( 10.000000 ),
                    ['cloudCountRange'] = FLOAT( 0.000000 ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 256.647, 11.9165, 259.124 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '5',
    next_group_id = '6',
    next_unit_id = '53',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Player'] =  
        {
            personality = '',
            plans = '/maps/scca_tutorial/scca_tutorial_playerplanlist.lua',
            color = 2,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Player_Aeon_CDR'] = {
                        type = 'ual0001',
                        orders = '',
                        platoon = '',
                        Position = { 132.960388, 20.513594, 366.047729 },
                        Orientation = { 0.000000, 0.000000, 0.000000 },
                    },
                    ['Player_CDR'] = {
                        type = 'uel0001',
                        orders = '',
                        platoon = '',
                        Position = { 143.500000, 20.712891, 349.500000 },
                        Orientation = { 0.000000, 0.000000, 0.000000 },
                    },
                    ['WRECKAGE'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_7'] = {
                                type = 'ura0104',
                                orders = '',
                                platoon = '',
                                Position = { 423.500000, 17.500000, 163.500000 },
                                Orientation = { 0.000000, -1.466077, 0.000000 },
                            },
                            ['UNIT_4'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 230.500000, 18.337891, 285.500000 },
                                Orientation = { 0.000000, 0.349066, 0.000000 },
                            },
                            ['UNIT_8'] = {
                                type = 'urs0201',
                                orders = '',
                                platoon = '',
                                Position = { 366.500000, 19.478516, 275.500000 },
                                Orientation = { 0.000000, -1.998402, 0.000000 },
                            },
                            ['UNIT_5'] = {
                                type = 'ues0302',
                                orders = '',
                                platoon = '',
                                Position = { 194.500000, 18.042969, 212.500000 },
                                Orientation = { 0.000000, 1.055925, 0.000000 },
                            },
                        },
                    },
                    ['Player_Cybran_CDR'] = {
                        type = 'url0001',
                        orders = '',
                        platoon = '',
                        Position = { 157.251953, 20.665873, 365.080475 },
                        Orientation = { 0.000000, 0.000000, 0.000000 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Instructor'] =  
        {
            personality = '',
            plans = '',
            color = 5,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Cybran'] = 'Enemy',
                ['Player'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Instructor_Unit'] = {
                        type = 'uec1902',
                        orders = '',
                        platoon = '',
                        Position = { 128.500000, 20.621094, 325.500000 },
                        Orientation = { 0.000000, 0.000000, 0.000000 },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Cybran'] =  
        {
            personality = '',
            plans = '/maps/scca_tutorial/scca_tutorial_cybranplanlist.lua',
            color = 0,
            faction = 2,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['CybranBase'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_37'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 378.500000, 20.449219, 142.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_2'] = {
                                type = 'url0001',
                                orders = '',
                                platoon = '',
                                Position = { 367.500000, 20.640625, 150.500000 },
                                Orientation = { 0.000000, 0.663225, 0.000000 },
                            },
                            ['UNIT_40'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 380.500000, 20.099609, 136.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_24'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 370.500000, 20.564453, 142.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_32'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 381.500000, 20.595703, 154.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_41'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 382.500000, 19.927734, 136.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_14'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 369.500000, 20.677734, 156.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_30'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 20.839844, 160.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_19'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 373.500000, 20.662109, 154.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_42'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 384.500000, 19.710938, 136.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_18'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 371.500000, 20.671875, 154.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_47'] = {
                                type = 'urb2109',
                                orders = '',
                                platoon = '',
                                Position = { 439.500000, 17.500000, 79.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_27'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 368.500000, 20.611328, 144.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_45'] = {
                                type = 'urb2109',
                                orders = '',
                                platoon = '',
                                Position = { 442.500000, 17.500000, 142.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_33'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 379.500000, 20.597656, 152.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_22'] = {
                                type = 'urb3101',
                                orders = '',
                                platoon = '',
                                Position = { 369.500000, 20.667969, 154.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_20'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 375.500000, 20.642578, 154.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_17'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 369.500000, 20.708984, 162.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_39'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 378.500000, 20.328125, 138.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_38'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 378.500000, 20.400391, 140.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_12'] = {
                                type = 'urb1202',
                                orders = '',
                                platoon = '',
                                Position = { 370.500000, 20.587891, 144.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_11'] = {
                                type = 'urb1202',
                                orders = '',
                                platoon = '',
                                Position = { 381.500000, 20.574219, 152.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_44'] = {
                                type = 'urb0203',
                                orders = '',
                                platoon = '',
                                Position = { 446.000000, 17.500000, 116.000000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_50'] = {
                                type = 'urb2104',
                                orders = '',
                                platoon = '',
                                Position = { 448.500000, 17.500000, 126.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_13'] = {
                                type = 'urb0301',
                                orders = '',
                                platoon = '',
                                Position = { 374.500000, 20.664063, 159.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_10'] = {
                                type = 'urb1202',
                                orders = '',
                                platoon = '',
                                Position = { 372.500000, 20.705078, 166.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_15'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 369.500000, 20.697266, 158.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_48'] = {
                                type = 'urb2104',
                                orders = '',
                                platoon = '',
                                Position = { 449.500000, 17.500000, 104.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_49'] = {
                                type = 'urb2104',
                                orders = '',
                                platoon = '',
                                Position = { 456.500000, 17.500000, 116.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_26'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 370.500000, 20.609375, 146.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_35'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 383.500000, 20.535156, 152.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_34'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 381.500000, 20.546875, 150.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_46'] = {
                                type = 'urb2109',
                                orders = '',
                                platoon = '',
                                Position = { 472.500000, 17.500000, 114.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_21'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 377.500000, 20.626953, 154.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_31'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 359.500000, 20.783203, 158.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_36'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 378.500000, 20.490234, 144.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_28'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 20.701172, 156.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_16'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 369.500000, 20.708984, 160.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_43'] = {
                                type = 'urb1101',
                                orders = '',
                                platoon = '',
                                Position = { 386.500000, 19.453125, 136.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_23'] = {
                                type = 'urb0202',
                                orders = '',
                                platoon = '',
                                Position = { 383.500000, 20.185547, 141.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_9'] = {
                                type = 'urb1202',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 20.759766, 158.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_25'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 372.500000, 20.564453, 144.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_29'] = {
                                type = 'urb1106',
                                orders = '',
                                platoon = '',
                                Position = { 363.500000, 20.716797, 158.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
