
PlanetInfo = {
    SCCA_A01 = {
        Name = '<LOC planet_info_0000>Joust',
        Planet = '<LOC planet_info_0001>Rigel',
        PlanetMov = 'planet_rigel.sfd',
        Terrain = '<LOC planet_info_0002>Tundra',
        Location = { .48, .43 },
    },
    SCCA_A02 = {
        Name = '<LOC planet_info_0003>Machine Purge',
        Planet = '<LOC planet_info_0004>Zeta Canis',
        PlanetMov = 'planet_zetacanis.sfd',
        Terrain = '<LOC planet_info_0005>Desert',
        Location = { .52,.62 },
    },
    SCCA_A03 = {
        Name = '<LOC planet_info_0006>High Tide',
        Planet = '<LOC planet_info_0007>Matar',
        PlanetMov = 'planet_matar.sfd',
        Terrain = '<LOC planet_info_0008>Tropical',
        Location = { .33,.29 },
    },
    SCCA_A04 = {
        Name = '<LOC planet_info_0009>Entity',
        Planet = '<LOC planet_info_0010>Procyon',
        PlanetMov = 'planet_procyon.sfd',
        Terrain = '<LOC planet_info_0011>Black Rock',
        Location = { .55,.65 },
    },
    SCCA_A05 = {
        Name = '<LOC planet_info_0012>Shining Star',
        Planet = '<LOC planet_info_0013>Eridani',
        PlanetMov = 'planet_eridani.sfd',
        Terrain = '<LOC planet_info_0014>Red Rock', 
        Location = { .42, .35 },
    },
    SCCA_A06 = {
        Name = '<LOC planet_info_0015>Beginnings',
        Planet = '<LOC planet_info_0016>Earth',
        PlanetMov = 'planet_earth.sfd',
        Terrain = '<LOC planet_info_0017>Tropical',
        Location = { .41, .40 },
    },
    SCCA_R01 = {
        Name = '<LOC planet_info_0018>Liberation',
        Planet = '<LOC planet_info_0019>Theban Pi-2',
        PlanetMov = 'planet_theban2.sfd',
        Terrain = '<LOC planet_info_0020>Desert',
        Location = { .44, .57 },
    },
    SCCA_R02 = {
        Name = '<LOC planet_info_0021>Artifact',
        Planet = '<LOC planet_info_0022>Orionis',
        PlanetMov = 'planet_orionis.sfd',
        Terrain = '<LOC planet_info_0023>Lava',
        Location = { .72,.40 },
    },
    SCCA_R03 = {
        Name = '<LOC planet_info_0024>Defrag',
        Planet = '<LOC planet_info_0025>Minerva',
        PlanetMov = 'planet_minerva.sfd',
        Terrain = '<LOC planet_info_0026>Evergreen',
        Location = { .38,.86 },
    },
    SCCA_R04 = {
        Name = '<LOC planet_info_0027>Mainframe Tango',
        Planet = '<LOC planet_info_0010>Procyon',
        PlanetMov = 'planet_procyon.sfd',
        Terrain = '<LOC planet_info_0029>Black Rock',
        Location = { .56,.65 },
    },
    SCCA_R05 = {
        Name = '<LOC planet_info_0030>Unlock',
        Planet = '<LOC planet_info_0031>Pollux', 
        PlanetMov = 'planet_pollux.sfd',
        Terrain = '<LOC planet_info_0032>Red Rock',
        Location = { .45,.52 },
    },
    SCCA_R06 = {
        Name = '<LOC planet_info_0033>Freedom',
        Planet = '<LOC planet_info_0016>Earth',
        PlanetMov = 'planet_earth.sfd',
        Terrain = '<LOC planet_info_0035>Tropical',
        Location = { .42, .39 },
    },
    SCCA_E01 = {
        Name = '<LOC planet_info_0036>Black Earth',
        Planet = '<LOC planet_info_0037>Capella',
        PlanetMov = 'planet_capella.sfd',
        Terrain = '<LOC planet_info_0038>Evergreen',
        Location = { .35, .68 },
    },
    SCCA_E02 = {
        Name = '<LOC planet_info_0039>Snow Blind',
        Planet = '<LOC planet_info_0040>Luthien',
        PlanetMov = 'planet_luthien.sfd',
        Terrain = '<LOC planet_info_0041>Tundra',
        Location = { .39,.29 },
    },
    SCCA_E03 = {
        Name = '<LOC planet_info_0042>Metal Shark', 
        Planet = '<LOC planet_info_0007>Matar',
        PlanetMov = 'planet_matar.sfd',
        Terrain = '<LOC planet_info_0044>Tropical',
        Location = { .33,.29 },
    },
    SCCA_E04 = {
        Name = '<LOC planet_info_0045>Vaccine',
        Planet = '<LOC planet_info_0025>Minerva',
        PlanetMov = 'planet_minerva.sfd',
        Terrain = '<LOC planet_info_0047>Evergreen',
        Location = { .38,.86 },
    },
    SCCA_E05 = {
        Name = '<LOC planet_info_0048>Forge',
        Planet = '<LOC planet_info_0049>Pisces IV',
        PlanetMov = 'planet_piscesIV.sfd',
        Terrain = '<LOC planet_info_0050>Lava',
        Location = { .40,.46 },
    },
    SCCA_E06 = {
        Name = '<LOC planet_info_0051>Stone Wall',
        Planet = '<LOC planet_info_0016>Earth',
        PlanetMov = 'planet_earth.sfd',
        Terrain = '<LOC planet_info_0053>Tropical',
        Location = { .42, .39 },
    },
    Seraphim = {
        Name = '<LOC planet_info_0054>Seraphim',
        Planet = '<LOC planet_info_0055>Seraphim',
        PlanetMov = 'planet_.sfd',
        Terrain = '<LOC planet_info_0056>paradise',
        Location = { .59, .18 },
    },
}